# https://help.github.com/en/actions

# https://github.com/actions
# https://github.com/actions/checkout
# https://github.com/actions/setup-node

# https://docs.github.com/en/actions/guides/building-and-testing-nodejs
# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

name: Node.js CI on Push

on: 
  push:
    paths:
    - '!.github/**'

jobs:
  npm-test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 3
    - name: Setup Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Show node & npm versions, environment
      run: |
        node --version
        npm --version
        env
        ls -l /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk || true
    - name: Install dependencies
      run: npm ci
    - name: Run test
      run: npm run test
      env:
        CI: true
