name: Node CI on Push

on: [push]

jobs:
  npm-test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [8.x, 10.x, 12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      run: |
        node --version
        npm --version
    - name: Install dependencies
      run: |
        npm ci
    - name: Run test
      run: |
        npm run test
      env:
        CI: true
