name: Test Docker on Dispatch

on: repository_dispatch

jobs:
  test-docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Show environment
      run: env
    - name: Show event
      run: cat $GITHUB_EVENT_PATH
    - name: Show Docker
      run: docker info
    - name: Run the test script
      run: bash .github/workflows/action-test-docker.sh
